M48
; DRILL file {KiCad 9.0.0} date 2025-04-07T15:36:51+0200
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2025-04-07T15:36:51+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.750
%
G90
G05
T1
X-29050Y75
X-29050Y-48925
X28950Y75
X28950Y-48925
M30
